### PR TITLE
fix: Instagram API strikes

### PR DESCRIPTION
**Pull request by ArvinZJC**
There are 2 necessary changes required:

1. Additional environment variables `IG_EMAIL` and `IG_PWD`: an Instagram account disabling two-factor authentication is required.
2. KV namespace configuration: see [the relevant docs](https://developers.cloudflare.com/workers/runtime-apis/kv#kv-bindings). In brief, one way is to use the command `wrangler kv:namespace create "KV" <--preview>` and add the console output as follows to the file `wrangler.toml`

```sh
kv_namespaces = [
    { binding = "KV", id = "XXX", preview_id = "XXX" }
]
```

Please note that `binding` must have the value `KV`. With all these configured, this PR should solve #33, though limitations exist.

### CODE REVIEW

**Comment by spencerwooo** [comment]
closing this in favor of new release

**Comment by ArvinZJC** [comment]
哥哥真棒

**Comment by spencerwooo** [comment]
要是用 KV 来持久化 Cookie 的话，这里有个例子：

https://github.com/spencerwooo/substats/blob/63b8902436df225f905ff1d1ba02b85c759f851f/src/providers/inoreader.ts#L7-L46

Instagram 的话原理是一样的，但是我也不知道为什么我 Inoreader 就是拿不到 Cookie，你要不要试试？目前手动设置的 Cookie 是一个月 Expire 的。

- https://developers.cloudflare.com/workers/platform/environment-variables#environmental-variables-with-module-workers

**Comment by ArvinZJC** [comment]
> 要是用 KV 来持久化 Cookie 的话，这里有个例子：
> 
> https://github.com/spencerwooo/substats/blob/63b8902436df225f905ff1d1ba02b85c759f851f/src/providers/inoreader.ts#L7-L46
> 
> Instagram 的话原理是一样的，但是我也不知道为什么我 Inoreader 就是拿不到 Cookie，你要不要试试？目前手动设置的 Cookie 是一个月 Expire 的。
> 
> * https://developers.cloudflare.com/workers/platform/environment-variables#environmental-variables-with-module-workers

好嘞，加 TODO 了，容我先完成一些其他的 tasks 🐌

**Pull request closed without merging**
